version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://suaib8211:cCzBqM7AZRAuOVbK@cluster0.2dsysod.mongodb.net/
      RABBITMQ_URI: amqp://rabbitmq:5672
      JWT_SECRET: 891bd404867bcb0051cb8fb204cfa8221886aca21d7a6c04d1c84cda71214613
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management port

volumes:
  mongo_data:
